brunch/brunch.github.io

app/skeletons.jade

@es128 @paulmillr for your consideration and approval. App coming together on [`develop`](https://github.com/jhabdas/brunch-with-emmett/tree/develop) branch.

Add Skeleton and update Panache stargazer count

---

app/plugins.jade

Hey guys,
Guess what? `fb-flo-brunch` is finally here, and it's awesome! Figured I'd add it to the list, next to its "colleagues".

Added link to fb-flo-plugin -- finally!

---

app/skeletons.jade

Hello! I added my new skeleton with some interesting features.

Added Brunch Getleman Set

---

app/plugins.jade

Re-add autoprefixer-brunch and deprecate it

---

examples.html

added logo (with link) of polish software house I work for

added TouK logo to example

---

examples.html

(re)added logo (with link) of polish software house I work for
removed by #127, it looks to me like a mistake

(re)added TouK logo to example

---

plugins.json

Added a new plugin called Vue Brunch which adds support to Brunch for pre-compiling single file Vue components.

Added Vue Brunch

---

plugins.json

Moved Vue Brunch to the bottom as requested.

Moved to bottom

---

source/app/assets/_docs/testing.md

Just a quick one, caught a typo on the testing page.

Fix for typo on testing page

---

source/app/assets/_docs/config.md

The preCompile hook was undocumented, so I just threw a little something together.
Also, there was a typo in the link for plugins, so I fixed that too :)

Add preCompile; fix plugins link.

---

source/app/assets/_docs/using-modules.md

Hi, sorry for the small PR, but this previous/next threw me off for a minute as I was reading the docs. Thanks!

Fix typo in using-modules.md

---

plugins.json

Add thomastorfs/static-marko-brunch plugin

Add thomastorfs/static-marko-brunch plugin

---

source/app/assets/_docs/config.md

Complements https://github.com/brunch/brunch/pull/1445.

Add documentation for sourceMaps' "inline" option.

---

source/app/assets/index.jade

Tweaked the tagline so it's short and sweet.

Concise tagline

---

plugins.json

Added https://github.com/prashnts/typeset-brunch

Add typeset-brunch

---

source/app/assets/_docs/plugins.md

config and plugins are always objects

---

plugins.json

jscc adds conditional compilation and variable replacement support to brunch.

Include jscc-brunch

---

source/app/assets/_docs/using-plugins.md

Related to https://github.com/brunch/brunch/issues/1377

Add note on plugin order of execution

---

plugins.json

Pug v2.x support for dynamic and static templates

Add pugjs-brunch to plugins

---

plugins.json

Hello!
This PR adds [grunticon-brunch](https://www.npmjs.com/package/grunticon-brunch) to the plugins list. Let me know if everything is in order.
Cheers!

Adds grunticon-brunch to the plugin list

---

docs/getting-started.html
docs/using-plugins.html
source/app/assets/_docs/getting-started.md
source/app/assets/_docs/using-plugins.md

Fix brunch/brunch#1486

---

docs/config.html
source/app/assets/_docs/config.md

`[\\/]` -> `\/` in regular expressions

Replace `[\\/]` -> `\/`

---

.travis.yml

Build only source branch

---

app/assets/_docs/config.md

Remove defaults values for `conventions` field.

Update `conventions` section

---

app/assets/_layouts/_docs.jade

I've noticed these links were broken

Fix 'Edit on GitHub' links

---

app/assets/_docs/config.md

Close https://github.com/brunch/brunch/issues/1481#issuecomment-241268455

Add section on renaming 'app' folder in docs. Close brunch/brunch#1481

---

app/init.js

Fix broken routing in development mode. 

---

app/assets/plugins.json

Since _javascript-brunch_ is deprecated

Remove deprecated javascript-brunch

---

app/assets/plugins.json

Related to https://github.com/brunch/typescript-brunch/pull/31

Merge typescript-brunch and brunch-typescript

---

app/assets/plugins.json

Adds [kssbrunch](https://github.com/FaKeller/kss-brunch) to the list of Brunch plugins

Adding kssbrunch to plugins.json

---

app/assets/plugins.json

Gonna transfer to Brunch org, but for now I'm not sure about implementation. 
Link: [raw-brunch](https://github.com/denysdovhan/raw-brunch)

Add raw-brunch plugin

---

app/assets/plugins.json

https://github.com/SilbinaryWolf/brunch-tumblr-theme-parser
https://www.npmjs.com/package/brunch-tumblr-theme-parser

Add brunch-tumblr-theme-parser to plugins.json

---

app/assets/_docs/config.md

In my opinion, the part about the entryPoints was a little bit misleading. I think it's important to highlight, that in most cases, you do not need joinTo AND entryPoints. And as far as I understand, joinTo is not always required.

improve the documentation on entryFiles

---

app/assets/_layouts/_default.jade
brunch-config.js
package.json

test refactored appcache on prod. let's start with default options and move forward step by step.

add appcache

---

app/assets/plugins.json

I've built a stylelint plugin. I've add CI and simple linting. It's been published to npm.

Add stylelint plugin

---

app/assets/plugins.json

add brunch plugin - 'adaptive-brunch'

add plugins

---

app/assets/plugins.json

More info you can find in readme:
https://github.com/Shalimov/brunch-feature-switcher

Add brunch-feature-switcher plugin to plugins.json

---

app/assets/plugins.json

Adding my uglify-es-brunch plugin to the minifiers list.

Adding uglify-es-brunch

---

app/assets/_docs/config.md

* Added some links in less common options
* Fixed line break in sourceMaps doc
* Updated notifications doc (fixes #275)

Fix a line break, links and notifications doc
